/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name\
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyFooter {
    'date': string;
    'linkArray'?: string;
    'name': string;
  }
  interface MyLoading {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLMyFooterElement extends Components.MyFooter, HTMLStencilElement {}
  var HTMLMyFooterElement: {
    prototype: HTMLMyFooterElement;
    new (): HTMLMyFooterElement;
  };

  interface HTMLMyLoadingElement extends Components.MyLoading, HTMLStencilElement {}
  var HTMLMyLoadingElement: {
    prototype: HTMLMyLoadingElement;
    new (): HTMLMyLoadingElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'my-footer': HTMLMyFooterElement;
    'my-loading': HTMLMyLoadingElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name\
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface MyFooter extends JSXBase.HTMLAttributes<HTMLMyFooterElement> {
    'date'?: string;
    'linkArray'?: string;
    'name'?: string;
  }
  interface MyLoading extends JSXBase.HTMLAttributes<HTMLMyLoadingElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'my-footer': MyFooter;
    'my-loading': MyLoading;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


